### ISSUE TITLE
Documentation generation doesn't recognize `markdown`

### ISSUE THREAD

**Issue by cspwizard** [namely/docker-protoc#98]
Documentation generation doesn't recognize `markdown`
```--with-docs FORMAT   Generate documentation (FORMAT is optional - see https://github.com/pseudomuto/protoc-gen-doc#invoking-the-plugin)```

according to the link above:
```The format may be one of the built-in ones ( docbook, html, markdown or json) or the name of a file containing a custom Go template.```

but when I try to generate java classes with documents (```docker run --rm -v `pwd`:/defs namely/protoc-all -d . -o ./out/test --lint --with-docs markdown -l java```) there is an error instead of documentation:
```
Generating java files for . in ./out/test
2018/10/25 07:59:37 Invalid parameter: markdown
--doc_out: protoc-gen-doc: Plugin failed with status code 1. 
```
How this could be fixed?

**Comment by kryptonat** [comment]
I'm getting the same issue here with doc generation. Any resolve?

**Comment by kryptonat** [comment]
Nvm, found out the correct way of invoking doc generation. See

https://github.com/namely/docker-protoc/blob/0e09fbacd85cad354b173a298c54f91a9ec1e945/all/entrypoint.sh#L39

https://github.com/namely/docker-protoc/blob/0e09fbacd85cad354b173a298c54f91a9ec1e945/all/entrypoint.sh#L104-L111

So instead of 
`docker run --rm -v `pwd`:/defs namely/protoc-all -d . -o ./out/test --lint --with-docs markdown -l java`

It would be
`docker run --rm -v `pwd`:/defs namely/protoc-all -d . -o ./out/test --lint --with-docs 'markdown,docs.md' -l java`

**Comment by ido-namely** [comment]
Thank you @cspwizard for opening the issue and 
thanks you @kryptonat for posting a solution.
